language: python
python: 2.7
env:
  - TOX_ENV=py26-django14
  - TOX_ENV=py26-django15
  - TOX_ENV=py26-django16
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=coverage
  global:
  - secure: J/5lMe5kssOijDOrxivPocuPcwaiOr0VxGxmMgKkLYHOVCUujVCNO32Ze/70KXmvyzRZx7K9yeER0qP1AcY/Zg8wTJi58nefbK9lnbu6/K6OQovj4fxUAZtZkB7X4CBvrUYKCeeVd+zJw31WC2v6Vtp3mh4irIm/TPIpeyoegmQ=
  - secure: ilN2b4RV4+//9N2DnFGh/hfDQS9ahBX6mY+OwWX72eqRlUyvt+eYGgljscWKEtDdVoA0SOSbZ7ghS2F9R+JsglYuyE//cb6DMsFa3+CW3I/Jl59nqKIgJkrmC1CrVSWmG/uISE0prITpIBH/3P5rT4EvqFQIfQ1WItAwtAmZKak=
  - secure: j9R74s5cwHWoGgQlIVqRj56gD+16wzGI7XIPFJ11yWDlgrftR0vkgiPlfgK5KKga4LOJBI2m92zgzr2OC9pgkvYjFR+i206F2cN2KbH2P8rFZtECp+o2uHBIhuZ8xOvw4TbxUNRd/ej6E4eKNcRvavwzfEwWO4C4v6FhC2rr5xk=
  - secure: NHsCChxiQJw07EUsqs2mtmmppApN8DLAB79JVeKoptQaxqxtzinL7QXxugAc0BNxvC3iCtTY5/232RyRn9dNNzY5Jq/b5YIsJJTMtAMTtY5xuJn8TTYV+TB5G31k9fnAAiqhdmdo7m7E6OSDxIYv44k147W43T0+nLlxCLlADew=
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
